name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Poetry Install
        uses: knowsuchagency/poetry-install@v2
        with:
          # Have poetry create a virtualenv for the project on installation.
          create-virtualenv: true

      - name: Run the Pytest suite
        run: poetry run pytest
        env:
          MUSIC_ROOT: /music/root
